CakeZ/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cakeshop.urls')),
    path('authentication/', include('authentication.urls')),
]

authentication/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = 'authentication'

urlpatterns = [
    path('', views.get_index, name='home'),
    path('register/', views.get_register, name='register'),
    path('login/', views.get_login, name='login'),
    path('logout', views.get_logout, name='logout')
]

cakeshop/urls.py
from django.urls import path
from . import views

app_name = 'cakeshop'

urlpatterns = [
    path('', views.Home.home, name='home'),
    path('cake/<int:pk>/', views.Shop.cake_detail, name='cake_detail'),
    path('cate/<int:pk>/', views.Shop.cate_detail, name='cate_detail'),
    path('shop', views.Shop.cakes_list, name='shop'),
    path('addtocart/<int:pk>/', views.Cart.cart_add, name='add_to_cart'),
    path('cart', views.Cart.cart_list, name='cart'),
    path('search', views.Shop.search, name='search'),
    path('update/<int:pk>/', views.Cart.cart_update, name='update_item'),
    path('remove/<int:pk>/', views.Cart.cart_remove, name='remove_item'),
    path('bill/<int:pk>/', views.BillView.get_bill, name='bill'),
    path('bill/create/', views.BillView.create_bill, name='create_bill'),
    path('history/', views.BillView.get_all_bill, name='purchase_history'),
]

cakeshop/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    class Meta:
        verbose_name_plural = 'Categories'
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name

class Cake(models.Model):
    name = models.CharField(max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    quantity = models.IntegerField()
    description = models.TextField()
    image_url = models.TextField(null=True, blank=True)

    def __str__(self):
        return self.name
    
    @staticmethod
    def search(query):
        return Cake.objects.filter(
            Q(name__icontains=query) | 
            Q(category__name__icontains=query) |
            Q(price__icontains=query) |
            Q(quantity__icontains=query) |
            Q(description__icontains=query)
        ).distinct()
        
class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    cake = models.ForeignKey(Cake, on_delete=models.CASCADE)
    quantity = models.IntegerField()

class Bill(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField()
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    address = models.CharField(max_length=255)
    town_city = models.CharField(max_length=50)
    phone_number = models.CharField(max_length=12)
    add_information = models.TextField(max_length=500, null=True, blank=True)
    cake_list = models.JSONField()
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)
    def __str__(self) -> str:
        return self.user.username

cakeshop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Cake, Order, Bill
from django.shortcuts import redirect
import json
from django.views import View
from django.urls import reverse
from django.core.paginator import Paginator
# class


class Home(View):
    def home(request):
        categories = Category.objects.all()
        cakes = Cake.objects.all().order_by('-id')
        if request.user.is_authenticated:
            Cart.switch_to_order(request)
            orders = Order.objects.filter(user=request.user)
            count = len(orders)
            request.session['count'] = count
        else:
            cart = Cart.get_cart(request)
            count = len(cart)
            request.session['count'] = count
        context = {'categories': categories, 'cakes': cakes}

        return render(request, 'cakeshop/index.html', context)


class Shop(View):
    def cakes_list(request):
        cakes = Cake.objects.all().order_by('-id')

        categories = Category.objects.all()
        cheap_cakes = Cake.objects.all().order_by('price')[:20]
        # chia danh sách sản phẩm thành các trang chứa 10 sản phẩm mỗi trang
        paginator = Paginator(cakes, 9)
        # lấy số trang được yêu cầu từ query string
        page_number = request.GET.get('page')
        # trả về đối tượng trang được yêu cầu
        page_obj = paginator.get_page(page_number)

        if request.user.is_authenticated == False:
            cart = Cart.get_cart(request)
            count = len(cart)
            request.session['count'] = count
        else:
            orders = Order.objects.filter(user=request.user)
            count = len(orders)
            request.session['count'] = count
        context = {'cakes': page_obj, 'categories': categories, 'count': count,
                   'cheap_cakes': cheap_cakes, 'modals': cakes}
        return render(request, 'cakeshop/products.html', context)

    def search(request):
        query = request.GET.get('query')
        if query:
            cakes = Cake.search(query)
        else:
            cakes = Cake.objects.all()

        categories = Category.objects.all()

        cheap_cakes = Cake.objects.all().order_by('price')[:20]
        context = {'categories': categories, 'cakes': cakes,
                   'cheap_cakes': cheap_cakes, 'modals': cheap_cakes}
        return render(request, 'cakeshop/products.html', context)

    def cake_detail(request, pk):
        cake = get_object_or_404(Cake, pk=pk)
        return render(request, 'cakeshop/cake_detail.html', {'cake': cake})

    def cate_detail(request, pk):
        categories = Category.objects.all()
        cakes = Cake.objects.filter(category=pk)
        cheap_cakes = Cake.objects.all().order_by('price')[:20]
        context = {'categories': categories,
                   'cakes': cakes, 'cheap_cakes': cheap_cakes, 'modals': cheap_cakes, 'activeId': pk}
        return render(request, ['cakeshop/products.html', 'cakeshop/base.html'], context)


class Cart(View):
    @staticmethod
    def switch_to_order(request):
        cart = Cart.get_cart(request)
        username = request.user
        print(username)
        if len(cart) != 0 and username != None:
            for item in cart:
                try:
                    order = Order.objects.get(
                        user=username, cake_id=item['id'])
                    order.quantity += item['quantity']
                    order.save()
                except Order.DoesNotExist:
                    order = Order.objects.create(
                        user=username, cake_id=item['id'], quantity=item['quantity'])
                    print(order)
                    order.save()
            del request.session['cart']

    @staticmethod
    def get_cart(request):
        cart = request.session.get('cart', [])
        if not isinstance(cart, list):
            cart = list(cart.value())
        return cart

    def cart_list(request):
        cart = []
        if request.user.is_authenticated == False:
            cart = Cart.get_cart(request)
        else:
            username = request.user
            orders = Order.objects.filter(user=username)
            cakes = Cake.objects.all()
            total = 0
            for order in orders:
                for cake in cakes:
                    if cake.id == order.cake_id:
                        price = float(cake.price) * float(order.quantity)
                        total += price
                        new_item = {'id': order.id, 'name': cake.name,
                                    'image_url': cake.image_url, 'price': price, 'quantity': order.quantity}
                        cart.append(new_item)
            request.session['total'] = total
        context = {'carts': cart}
        # return render(request, 'cakeshop/cart.html', context)
        return render(request, 'cakeshop/shopping_cart.html', context)

    def cart_add(request, pk):
        cart = Cart.get_cart(request)
        cake_exit = False
        cake = get_object_or_404(Cake, pk=pk)
        total = 0
        quantity = int(request.POST.get('quantity', 0))

        if request.user.is_authenticated == False:
            for item in cart:
                if item['id'] == pk:
                    item['quantity'] += quantity
                    item['price'] = float(cake.price) + item['quantity']
                    cake_exit = True

            if not cake_exit:
                new_item = {'id': pk, 'name': cake.name, 'image_url': cake.image_url,
                            'price': float(cake.price), 'quantity': quantity}
                cart.append(new_item)
            count = len(cart)
            request.session['count'] = count
            request.session['cart'] = cart
            total = sum([float(item['price']) for item in cart])
        else:
            username = request.user
            try:
                order = Order.objects.get(user=username, cake_id=pk)
                order.quantity += quantity
                order.save()
            except Order.DoesNotExist:
                order = Order.objects.create(
                    user=username, cake_id=pk, quantity=quantity)
                order.save()
            orders = Order.objects.filter(user=username)
            count = len(orders)
            request.session['count'] = count

        request.session['total'] = total
        return redirect("/shop")

    def cart_update(request, pk):
        quantity = int(request.POST.get('quantity', 0))

        if request.user.is_authenticated == False:
            cart = Cart.get_cart(request)
            cake = get_object_or_404(Cake, pk=pk)
            for i, item in enumerate(cart):
                if item['id'] == pk:
                    if quantity == 0:
                        cart.pop(i)
                    else:
                        item['quantity'] = quantity
                        item['price'] = float(cake.price) * quantity
                    break
            request.session['cart'] = cart
            total = sum([float(item['price']) for item in cart])
            request.session['total'] = total

        else:
            username = request.user
            try:
                order = Order.objects.get(user=username, id=pk)
                order.quantity = quantity
                order.save()
            except Order.DoesNotExist:
                pass
        return redirect("/cart")

    def cart_remove(request, pk):
        total = 0
        if request.user.is_authenticated == False:
            cart = Cart.get_cart(request)
            for i, item in enumerate(cart):
                if item['id'] == pk:
                    cart.pop(i)
                    break
            request.session['cart'] = cart
            total = sum([float(item['price']) for item in cart])
            count = len(cart)
            request.session['count'] = count
        else:
            username = request.user
            try:
                order = Order.objects.get(user=username, id=pk)
                order.delete()
                orders = Order.objects.filter(user=username)
                cakes = Cake.objects.all()
                for itemOrder in orders:
                    for item in cakes:
                        if item.id == itemOrder.cake_id:
                            total += float(item.price) * \
                                float(itemOrder.quantity)
            except Order.DoesNotExist:
                pass
            count = len(orders)
            request.session['count'] = count

        request.session['total'] = total
        return redirect("/cart")


class BillView(View):
    def get_bill(request, pk):
        bill = get_object_or_404(Bill, pk=pk)
        cake_list = json.loads(bill.cake_list)
        context = {'bill': bill, 'cake_list': cake_list}
        return render(request, ['cakeshop/bill.html', 'cakeshop/purchase_history.html'], context)

    def create_bill(request):
        if request.user.is_authenticated == False:
            return redirect('/authentication/login/')
        else:
            username = request.user
            if request.method == 'POST':
                email = request.POST['email']
                first_name = request.POST['first_name']
                last_name = request.POST['last_name']
                address = request.POST['address']
                town_city = request.POST['town_city']
                phone_number = request.POST['phone_number']
                add_information = request.POST.get('add_information', '')

                cake_list = []
                total_price = 0
                orders = Order.objects.filter(user=username)
                cakes = Cake.objects.all()
                for order in orders:
                    for cake in cakes:
                        if cake.pk == order.cake_id:
                            cake_name = cake.name
                            quantity = order.quantity

cakeshop/templates/cakeshop/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
    {% block title %}

    {% endblock title %}
  </title>
  {% load static %}
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
    crossorigin="anonymous"></script>

  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css"
    integrity="sha512-iecdLmaskl7CVkqkXNQ/ZH/XLlvWZOJyj7Yy7tcenmpD1ypASozpmT/E0iPtmFIB46ZmdtAc9eNBvH0H/ZpiBw=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />

  <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"
    integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="shortcut icon" href="{% static 'img/shop_logo.png' %}" type="image/x-icon">

  {% block additionalCss %}

  {% endblock additionalCss %}





</head>

<body>


  <nav class="header navbar navbar-dark bg-transparent" aria-label="Dark offcanvas navbar">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <div class="navbar__logo" style="background-image: url('../../static/img/shop_logo.png');"></div>
      </a>
      <div class="btn-wrapper d-flex justify-content-center">
        <form class="search-box" role="search" method="get" action="{% url 'cakeshop:search' %}">
          <button class="btn-search">
            <i class="fas fa-search btn-search-icon"></i>
          </button>
          <input type="text" class="input-search" placeholder="Type to Search..." name="query">
        </form>
        <button class="navbar-toggler btn-bagshop-cover">
          <a class="text-white" href="{% url 'cakeshop:cart' %}">
            <i class="fas fa-bag-shopping btn-bagshop-icon">
              {% if request.session.count != 0 %}
              <div class="btn-bagshop-bacground-number">
                <span class="btn-bagshop-number">
                  {{ request.session.count }}
                </span>
              </div>
              {% endif %}
            </i>
          </a>
        </button>
        <button class="navbar-toggler" type="submit" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbarDark"
          aria-controls="offcanvasNavbarDark" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon text-dark"></span>
        </button>
      </div>
      <div class="offcanvas offcanvas-end background__offcanvas" tabindex="-1" id="offcanvasNavbarDark"
        aria-labelledby="offcanvasNavbarDarkLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarDarkLabel background__offcanvas-text">Welcome to
            CakeZ</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas"
            aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cakeshop:shop' %}">Products</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cakeshop:home' %}#about">About Us</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#contact">Contact Us</a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-link">
              <a class="nav-link" href="">{{ request.user }}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'cakeshop:purchase_history' %}">Purchase history</a>
            </li>
            <li class="nav-link" class="nav-item">
              <a class="nav-link" href="{% url 'authentication:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'authentication:login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'authentication:register' %}">Register</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </nav>

  {% block content %}

  {% endblock content %}

  <footer class="footer__color text-center text-lg-start bg-light text-muted">
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <div class="me-5 d-none d-lg-block">
        <span class="network__title">Get connected with us on social networks:</span>
      </div>
      <div class="network__wrapper">
        <a href="https://www.facebook.com/profile.php?id=100009744666886" class="me-4 text-reset">
          <i class="network__icon fab fa-facebook-f"></i>
        </a>
        <!-- <a href="" class="me-4 text-reset">
          <i class="network__icon fab fa-twitter"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="network__icon fab fa-google"></i>
        </a> -->
        <a href="https://www.instagram.com/thaitran1810/" class="me-4 text-reset">
          <i class="network__icon fab fa-instagram"></i>
        </a>
        <!-- <a href="" class="me-4 text-reset">
          <i class="network__icon fab fa-linkedin"></i>
        </a>
        <a href="" class="me-4 text-reset">
          <i class="network__icon fab fa-github"></i>
        </a> -->
      </div>
    </section>
    <section class="" id="contact">
      <div class="container-fluid text-center text-md-start mt-5">
        <div class="row mt-3">
          <div class="company_content-wrapper col-md-6 col-lg-3 mx-auto mb-4">
            <h6 class="text-uppercase footer__title fw-bold mb-4">
              <i class="fas fa-gem me-3"></i>Company name
            </h6>
            <p class="footer__content">
              There are many variations of passages of Lorem Ipsum available, but the majority have
              suffered alteration in some form, by injected humour, or randomised words which don't
              look even slightly believable. If you are going to use a passage of Lorem Ipsum, you
              need to be sure there isn't anything embarrassing hidden in the middle of text.
            </p>
          </div>
          <div class="col-md-6 col-lg-2 mx-auto mb-4">
            <h6 class="text-uppercase footer__title fw-bold mb-4">
              Categories
            </h6>

            {% for category in categories %}
            <p>
              <a href="{% url 'cakeshop:cate_detail' category.id %}"
                class="text-reset footer__content">{{category.name}}</a>
            </p>
            {% endfor %}
          </div>
          <div class="col-md-6 col-lg-2 mx-auto mb-md-0 mb-4">
            <h6 class="text-uppercase footer__title fw-bold mb-4">Contact</h6>
            <p class="footer__content"><i class="fas fa-home me-3"></i> Ho Chi Minh City</p>
            <p class="footer__content">
              <i class="fas fa-envelope me-3"></i>
              anhthaii1810@gmail.com
            </p>
            <p class="footer__content"><i class="fas fa-phone me-3"></i> + 84 343 323 560</p>
            <p class="footer__content"><i class="fas fa-print me-3"></i> + 84 343 323 560</p>
          </div>
          <div class="col-md-6 col-lg-4 mx-auto mb-4">
            <h6 class="text-uppercase footer__title fw-bold mb-4">
              Address
            </h6>
            <div class="mapouter">
              <div class="gmap_canvas">
                <iframe class="gmap_canvas-size" id="gmap_canvas"
                  src="https://maps.google.com/maps?q=331 nguyễn kiệm&t=&z=11&ie=UTF8&iwloc=&output=embed"
                  frameborder="0" scrolling="no" marginheight="0" marginwidth="0">
                </iframe>
                <style>
                  .mapouter {
                    position: relative;
                    text-align: right;
                    height: 100%;
                    width: 100%;
                  }
                </style>
                <style>
                  .gmap_canvas {
                    /* overflow: hidden; */
                    background: none !important;
                    height: 100% !important;
                    width: 100% !important;
                  }

                  .gmap_canvas-size {
                    width: 100%;
                    height: 82%;
                  }
                </style>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <div class="footer__text text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
      © 2023 Lam Vu Thanh Tai
    </div>
    <!-- Copyright -->
  </footer>


  <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
  <script type="text/javascript" src="https://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
  <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

  {% block additionalJs %}

  {% endblock additionalJs %}


</body>

</html>

cakeshop/templates/cakeshop/bill.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>Bill</title>
    <style>
        .bill {
            width: 80%;
            margin: 0 auto;
            font-size: 1.2em;
            }
            
            h1 {
            text-align: center;
            }
            
            p {
            margin-bottom: 10px;
            }

    </style>
  </head>
  <body>
    <div class="bill">
      <h1>Bill</h1>
      <p>User: {{ bill.user }}</p>
      <p>Email: {{ bill.email }}</p>
      <p>First Name: {{ bill.first_name }}</p>
      <p>Last Name: {{ bill.last_name }}</p>
      <p>Address: {{ bill.address }}</p>
      <p>Town/City: {{ bill.town_city }}</p>
      <p>Phone Number: {{ bill.phone_number }}</p>
      <p>Date: {{ bill.date }}</p>
      <p>Additional Information: {{ bill.add_information }}</p>
      <p>Cake: 
        <ul>
          {% for cake in cake_list %}
              <li>{{ cake.cake_name }} - {{ cake.quantity }}</li>
          {% endfor %}
        </ul>
      </p>
      <p>Total Price: {{ bill.total_price }}</p>
    </div>
  </body>
</html>

cakeshop/templates/cakeshop/create_bill.html
<!-- create_bill.html -->
{% extends 'cakeshop/base.html' %}
{% load static %}
{% block additionalCss %}
<link rel="stylesheet" href="{% static '/css/base.css' %}">
<link rel="stylesheet" href="{% static '/css/main.css' %}">
<link rel="stylesheet" href="{% static '/css/responsive.css' %}">
<link rel="stylesheet" href="{% static '/css/forminfo.css' %}">
{% endblock additionalCss %}
{% block content %}
<div class="form-cover" style="
    background-image: url(https://websitecukcukvn.misacdn.net/wp-content/uploads/2022/12/cua-hang-banh-ngot.jpg) !important;
    background-repeat: no-repeat !important;
    background-size: cover !important;
    width: 100%;
    height: 100%;
    ">
  <div class="form-wapper">
    <h1 class="form-tite">Create Bill</h1>
    <form method="post" class="form" style="width: auto;">
      {% csrf_token %}
      <div class="form__content-wrapper">
        <div class="form__content">
          <label class="form__label" for="first_name">First name:<span class="form__label-star">*</span> </label>
          <input class="form__input" placeholder="Type here !" type="text" name="first_name" id="first_name" required>
        </div>
        <div class="form__content">
          <label class="form__label" for="last_name">Last name:<span class="form__label-star">*</span></label>
          <input class="form__input" placeholder="Type here !" type="text" name="last_name" id="last_name" required>
        </div>
      </div>
      <div class="form__content">
        <label class="form__label" for="email">Email: <span class="form__label-star">*</span></label>
        <input class="form__input" placeholder="Type here !" type="email" name="email" id="email" required>
      </div>
      <div class="form__content">
        <label class="form__label" for="address">Address:<span class="form__label-star">*</span></label>
        <input class="form__input" placeholder="Type here !" type="text" name="address" id="address" required>
      </div>
      <div class="form__content">
        <label class="form__label" for="town_city">Town/City:<span class="form__label-star">*</span></label>
        <input class="form__input" placeholder="Type here !" type="text" name="town_city" id="town_city" required>
      </div>
      <div class="form__content">
        <label class="form__label" for="phone_number">Phone number:<span class="form__label-star">*</span></label>
        <input class="form__input" placeholder="Type here !" type="text" name="phone_number" id="phone_number" required>
      </div>
      <!-- <div class="form__content"> -->
        <label class="form__label" for="add_information">Note:</label>
        <br>
        <textarea class="form__textarea" name="add_information" id="add_information"></textarea>
      <!-- </div> -->

      <!-- <label for="cake">Cake:</label>
    <select name="cake" id="cake" required>
      {% for cake in cakes %}
      <option value="{{ cake.pk }}">{{ cake.name }}</option>
      {% endfor %}
    </select>
    <br>
    <label for="quantity">Quantity:</label>
    <input type="number" name="quantity" id="quantity" min="1" max="10" value="1" required> -->
      {% for cart in cart %}
      <div class="product">
        <!-- <form class="col-lg-7 product" action="{% url 'cakeshop:update_item' cart.id %}"
            method="post"> -->
        {% csrf_token %}
        <h4 class="product__name">{{ cart.name }}</h4>
        <input class="product__input" type="number" name="quantity" value="{{ cart.quantity }}">
        <p class="product__price">${{ cart.price }}</p>
        <!-- </form> -->
      </div>
      {% endfor %}

      {% if request.session.total %}
      <p class="product__totalprice">Total price: ${{ request.session.total }}</p>
      {% endif %}

      <input class="product__btn-submit" type="submit" value="Submit">
    </form>
  </div>
</div>
{% endblock %}